import { PricingPlan, CompetitorData } from './types';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free Forever',
    description: 'The Hook',
    monthlyPriceINR: 0,
    yearlyPriceINR: 0,
    monthlyCredits: 10,
    allowance: '10 Credits / Mo',
    features: [
      'Standard AI OCR',
      'Basic Export (JSON)',
      'Community Support',
      'Secure Cloud Storage (7-day)',
    ],
    cta: 'Get Started Free',
    note: 'Perfect to test the workflow',
  },
  {
    id: 'starter',
    name: 'Starter',
    description: 'The Freelancer',
    monthlyPriceINR: 1199,
    yearlyPriceINR: 11990,
    monthlyCredits: 150,
    allowance: '150 Credits / Mo',
    features: [
      '~450–750 Pages included',
      'Standard Support',
      'Personal Dashboard',
      'Direct API Access',
    ],
    cta: 'Start 7-Day Trial',
    note: 'Best for solo contractors',
  },
  {
    id: 'business',
    name: 'Business',
    description: 'The Sweet Spot',
    monthlyPriceINR: 2999,
    yearlyPriceINR: 29990,
    monthlyCredits: 1000,
    allowance: '1,000 Credits / Mo',
    features: [
      '~3,000–5,000 Pages included',
      'Priority Support (1h)',
      'Up to 3 Team Members',
      'Excel & CSV Export',
      '10% Rollover Credits',
    ],
    cta: 'Upgrade to Business',
    highlight: true,
    badge: 'Most Popular',
    note: 'Best for small firms',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'The Anchor',
    monthlyPriceINR: 12999,
    yearlyPriceINR: 129990,
    monthlyCredits: 5000,
    allowance: '5,000+ Credits / Mo',
    features: [
      'Unlimited Team Members',
      'Custom SLA & Invoicing',
      'Dedicated Account Manager',
      'Audit Logs & SSO',
      'Full Compliance Package',
    ],
    cta: 'Contact Sales',
    contactSales: true,
    note: 'Best for large organizations',
  },
];

export const COMPETITORS: CompetitorData[] = [
  {
    name: 'FinFlow AI (Business)',
    price: 2999,
    allowance: '1,000 Credits',
    costPerDoc: '₹2.99',
  },
  {
    name: 'DocuClipper (Basic)',
    price: 3250,
    allowance: '40 Documents*',
    costPerDoc: '₹81.25',
  },
  {
    name: 'AutoEntry',
    price: 5000,
    allowance: '100 Documents',
    costPerDoc: '₹50.00',
  },
];
